### PR TITLE
Add a tree widget displaying passed and failed tests

### PR DESCRIPTION
**Pull request by cboulanger**
I wasn't really happy with the console output since it was very hard to read. This adds a bit more eye candy so that you can immediately see the number of failed test. 

Bildschirmfoto 2020-03-17 um 09 48 00

### CODE REVIEW

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
way cool!

**Review by hkollmann — APPROVED** [review]

**Comment by hkollmann** [comment]
Cool!!

**Comment by cboulanger** [comment]
You're fast ... have you really run your tests first? :-)

**Comment by cboulanger** [comment]
Please feel free to further improve on the layout & logic - I have quickly hacked it by copying & pasting snippets from the demobrowser.

**Comment by cboulanger** [comment]
One could, for example, further split up the tree into namespaces, like the old testrunner did. but maybe having the class as a node and the tests as leafs is enough.

**Pull request merged**
